"""Init

Revision ID: 52f44fc4abbe
Revises: None
Create Date: 2014-10-30 19:26:24.676562

"""

# revision identifiers, used by Alembic.
revision = '52f44fc4abbe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
